import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const dir=new URL('./dist/',import.meta.url), evidence=new URL('./evidence/',import.meta.url);
await mkdir(evidence,{recursive:true});
const server=createServer(async(req,res)=>{try{const name=req.url==='/'?'index.html':req.url.slice(1);if(!/^[\w.-]+$/.test(name))throw Error();const data=await readFile(new URL(name,dir));res.setHeader('Content-Type',name.endsWith('.mjs')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/html');res.end(data)}catch{res.writeHead(404);res.end()}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'msedge',headless:true});const checks=[];
try{for(const [name,viewport] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){const context=await browser.newContext({viewport,acceptDownloads:true});const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>requests.push(r.url()));await page.goto(origin);await page.waitForFunction(()=>document.querySelector('#editor').value.length>10);
await page.locator('#check').click();assert.match(await page.locator('#result').innerText(),/Структура заполнена/);checks.push(name+': RU positive');
await page.locator('#language').selectOption('en');assert.match(await page.locator('#result').innerText(),/Structure complete/);assert.equal(await page.locator('html').getAttribute('lang'),'en');
await page.locator('#load').click();await page.locator('#editor').press('Control+Enter');assert.match(await page.locator('#result').innerText(),/Structure complete/);assert.equal(await page.evaluate(()=>document.activeElement.id),'result');checks.push(name+': EN keyboard validation and focus');
const valid=await page.locator('#editor').inputValue();await page.locator('#editor').fill('{}');assert.equal(await page.locator('#save-report').isDisabled(),true);await page.locator('#check').click();assert.match(await page.locator('#result').innerText(),/Needs attention/);assert.equal(await page.locator('#result li').count(),7);
for(const raw of ['','{broken','null','[]',' '.repeat(100001)]){await page.locator('#editor').fill(raw);await page.locator('#check').click();assert.match(await page.locator('#result').innerText(),/Needs attention/)}
const object=JSON.parse(valid);object.objective='x'.repeat(1000);await page.locator('#editor').fill(JSON.stringify(object));await page.locator('#check').click();assert.match(await page.locator('#result').innerText(),/Structure complete/);object.objective+='x';await page.locator('#editor').fill(JSON.stringify(object));await page.locator('#check').click();assert.match(await page.locator('#result').innerText(),/Needs attention/);checks.push(name+': negative, malformed, null, array, empty and length boundaries');
await page.locator('#editor').fill(valid);await page.locator('#check').click();const downloaded=page.waitForEvent('download');await page.locator('#save-report').click();const download=await downloaded;const report=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(report.valid,true);assert.equal('brief' in report,false);checks.push(name+': report download');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle!=='none'));checks.push(name+': width, no storage, visible keyboard focus');
await page.screenshot({path:new URL(name+'.png',evidence).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(requests.filter(x=>!x.startsWith(origin)),[]);checks.push(name+': no console errors or external requests');await context.close()}
await writeFile(new URL('test-results.json',evidence),JSON.stringify({date:new Date().toISOString(),browser:'Microsoft Edge headless / Playwright',checks,passed:checks.length},null,2));console.log(JSON.stringify({passed:checks.length,checks},null,2));}finally{await browser.close();await new Promise(r=>server.close(r))}
