import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {planCampaign,versionsToCsv,planToJson} from '../planner.mjs';
const input={durations:[15,30],channels:[{id:'social',label:'Social, "campaign"',aspectRatios:['9:16']},{id:'website',aspectRatios:['16:9','1:1']}],locales:['ru','en']};
test('channel-specific combinations and deterministic IDs',()=>{const r=planCampaign(input);assert.equal(r.valid,true);assert.equal(r.total,12);assert.equal(new Set(r.versions.map(v=>v.id)).size,12);assert.equal(r.versions.filter(v=>v.channelId==='social').every(v=>v.aspectRatio==='9:16'),true);const reverse={durations:[...input.durations].reverse(),channels:[...input.channels].reverse().map(c=>({...c,aspectRatios:[...c.aspectRatios].reverse()})),locales:[...input.locales].reverse()};assert.deepEqual(planCampaign(reverse).versions,r.versions)});
test('duplicates handled explicitly without multiplication',()=>{const r=planCampaign({durations:[15,15],channels:[{id:'web',aspectRatios:['16:9','16:9']},{id:'web',aspectRatios:['1:1']}],locales:['en','EN']});assert.equal(r.total,2);assert.equal(r.warnings.length,4);assert.equal(r.valid,true)});
test('invalid types, empty arrays and unknown metadata',()=>{for(const x of [null,[],{}, {...input,durations:[]},{...input,channels:[]},{...input,locales:[]},{...input,client:'private'}, {...input,channels:[{id:'web',aspectRatios:[],secret:'x'}]}])assert.equal(planCampaign(x).valid,false)});
test('duration boundaries reject NaN infinity zero negative fractions overflow',()=>{for(const n of [0,-1,NaN,Infinity,3601,1.5,'30'])assert.equal(planCampaign({...input,durations:[n]}).valid,false,String(n));for(const n of [1,3600])assert.equal(planCampaign({...input,durations:[n]}).valid,true)});
test('exact 1000 cap, above cap and input limits',()=>{const base={durations:Array.from({length:100},(_,i)=>i+1),channels:[{id:'web',aspectRatios:['16:9']}],locales:['ru','en','fr','de','es','it','pt','ar','ja','ko']};assert.equal(planCampaign(base).total,1000);const too=planCampaign({...base,locales:[...base.locales,'zh']});assert.equal(too.valid,false);assert.equal(too.total,0);assert.deepEqual(too.versions,[]);assert.equal(planCampaign({...input,durations:Array(101).fill(1)}).valid,false)});
test('unsafe labels, invalid ratios, locale and conflicting labels rejected',()=>{for(const label of ['=SUM(A1)',' +123','-cmd','@formula','x\ny','<script>','x\u0000y'])assert.equal(planCampaign({...input,channels:[{id:'web',label,aspectRatios:['16:9']}]}).valid,false,label);for(const ratio of ['0:9','16:0','1/1','100:1'])assert.equal(planCampaign({...input,channels:[{id:'web',aspectRatios:[ratio]}]}).valid,false);assert.equal(planCampaign({...input,locales:['en_US']}).valid,false);assert.equal(planCampaign({...input,channels:[{id:'x',label:'A',aspectRatios:['1:1']},{id:'x',label:'B',aspectRatios:['1:1']}]}).valid,false)});
test('JSON roundtrip, CSV RFC4180 quote and stable columns',()=>{const r=planCampaign(input);assert.deepEqual(JSON.parse(planToJson(r)),r);const csv=versionsToCsv(r.versions);assert.ok(csv.startsWith('id,channelId,channelLabel,aspectRatio,locale,durationSeconds\r\n'));assert.ok(csv.includes('"Social, ""campaign"""'));assert.equal(csv.trim().split('\r\n').length,13);assert.throws(()=>versionsToCsv([{...r.versions[0],channelLabel:'=1+1'}]));assert.throws(()=>versionsToCsv([{...r.versions[0],extra:'x'}]))});
test('localization and no mutation',()=>{const before=JSON.stringify(input);planCampaign(input);assert.equal(JSON.stringify(input),before);assert.notEqual(planCampaign(null,{language:'ru'}).errors[0].message,planCampaign(null).errors[0].message)});
test('CLI exits for valid invalid syntax and missing file',()=>{for(const [name,code]of [['valid.en.json',0],['invalid.json',1],['malformed.txt',2],['missing.json',2]]){const r=spawnSync(process.execPath,[fileURLToPath(new URL('../cli.mjs',import.meta.url)),fileURLToPath(new URL('../examples/'+name,import.meta.url))],{encoding:'utf8'});assert.equal(r.status,code,r.stderr);assert.ok(JSON.parse(r.stdout))}});

test('CSV parses back to original field values including commas and quotes',()=>{const expected=planCampaign(input).versions;const csv=versionsToCsv(expected);const rows=[];let row=[],field='',quoted=false;for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if(c==='\r'&&csv[i+1]==='\n'&&!quoted){row.push(field);rows.push(row);row=[];field='';i++;}else field+=c;}assert.equal(quoted,false);const header=rows.shift();const actual=rows.map(values=>Object.fromEntries(header.map((key,i)=>[key,key==='durationSeconds'?Number(values[i]):values[i]])));assert.deepEqual(actual,expected);});
