import test from 'node:test';
import assert from 'node:assert/strict';
import {createClient,ENDPOINT} from './client.mjs';
const response=result=>new Response(JSON.stringify({jsonrpc:'2.0',id:1,result}),{headers:{'content-type':'application/json'}});
test('fixed read-only tool request and protocol metadata',async()=>{let request;const client=createClient({fetchImpl:async(url,options)=>{request={url,...options};return response({isError:false,structuredContent:{ok:true,lineage:{version:'test'}}})}});const result=await client.run('brief');assert.equal(result.structuredContent.ok,true);assert.equal(request.url,ENDPOINT);assert.equal(request.redirect,'error');assert.equal(request.headers['mcp-protocol-version'],'2026-07-28');assert.equal(request.headers['mcp-name'],'get_brief_requirements');assert.equal(JSON.parse(request.body).params._meta['io.modelcontextprotocol/protocolVersion'],'2026-07-28');assert.equal(JSON.parse(request.body).params.arguments.locale,'en')});
test('tools/list validates names and readOnly annotations',async()=>{const c=createClient({fetchImpl:async()=>response({tools:[{name:'get_brief_requirements',annotations:{readOnlyHint:true}}]})});assert.equal((await c.run('list')).tools.length,1)});
test('reject unknown action before any request',async()=>{const c=createClient({fetchImpl:()=>{throw Error('request must not occur')}});await assert.rejects(()=>c.run('send_email'),/allowlist/);await assert.rejects(()=>c.run('https://example.com'),/allowlist/)});
test('malformed envelopes, ids, errors and unsafe tools rejected',async()=>{for(const body of ['broken','null',JSON.stringify({jsonrpc:'2.0',id:2,result:{}}),JSON.stringify({jsonrpc:'2.0',id:1,error:{code:-1,message:'bad'}}),JSON.stringify({jsonrpc:'2.0',id:1,result:{tools:[{name:'write',annotations:{readOnlyHint:false}}]}})]){const c=createClient({fetchImpl:async()=>new Response(body,{headers:{'content-type':'application/json'}})});await assert.rejects(()=>c.run('list'))}});
test('tool error and missing public structured contract rejected',async()=>{for(const result of [{isError:true},{structuredContent:{ok:false}},{content:[]}]){const c=createClient({fetchImpl:async()=>response(result)});await assert.rejects(()=>c.run('brief'))}});
test('HTTP failures, unsupported media type, large response rejected',async()=>{for(const r of [new Response('no',{status:403}),new Response('event: message',{headers:{'content-type':'text/event-stream'}}),new Response('x'.repeat(2097153),{headers:{'content-type':'application/json'}})]){const c=createClient({fetchImpl:async()=>r});await assert.rejects(()=>c.run('brief'))}});
test('timeout cancels a hanging transport',async()=>{const c=createClient({timeoutMs:15,fetchImpl:async(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}))});await assert.rejects(()=>c.run('brief'),/timeout/i)});
test('timeout limits enforced',()=>{for(const value of [0,-1,30001,NaN,'20'])assert.throws(()=>createClient({timeoutMs:value}),/timeout/)});


test('large valid method response under 2 MiB accepted',async()=>{const c=createClient({fetchImpl:async()=>response({structuredContent:{ok:true,data:{fixture:'x'.repeat(300000)}}})});assert.equal((await c.run('methods')).structuredContent.ok,true)});
